# Generated by Django 4.1.13 on 2023-12-07 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category_management',
            },
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.FloatField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.customerdetails')),
            ],
            options={
                'db_table': 'sold_product_management',
            },
        ),
        migrations.CreateModel(
            name='SoldBillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst', models.FloatField()),
                ('is_verified', models.BooleanField()),
                ('description', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.customerdetails')),
                ('products', models.ManyToManyField(to='inventory_management.category')),
            ],
            options={
                'db_table': 'sold_billing_details',
            },
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.vendordetails')),
            ],
            options={
                'db_table': 'purchased_product_management',
            },
        ),
        migrations.CreateModel(
            name='PurchasedBillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst', models.FloatField()),
                ('is_verified', models.BooleanField()),
                ('description', models.CharField(max_length=128)),
                ('products', models.ManyToManyField(to='inventory_management.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.vendordetails')),
            ],
            options={
                'db_table': 'purchased_billing_details',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.category')),
            ],
            options={
                'db_table': 'inventory_management',
            },
        ),
        migrations.CreateModel(
            name='InHouseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.departmentdetails')),
            ],
            options={
                'db_table': 'inhouse_product_management',
            },
        ),
    ]
