# Generated by Django 4.1.13 on 2023-12-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_category_id_alter_inhouseproducts_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
    ]
