# Generated by Django 4.1.13 on 2023-12-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_rename_category_id_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedbillingdetails',
            name='products',
        ),
    ]
