# Generated by Django 4.1.13 on 2023-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_management', '0002_alter_area_id_alter_building_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
