# Generated by Django 4.1.13 on 2023-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_management', '0003_building_latitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='scraped_id',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
