# Generated by Django 4.1.13 on 2023-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('node_addr', models.CharField(max_length=128)),
                ('condition', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
